from keras.src import testing

from segme.policy.align.gla import GlaFeatureAlignment


class TestBilinearFeatureAlignment(testing.TestCase):
    def test_layer(self):
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 1.0,
                "res_near": True,
                "in_norm": False,
                "in_mode": "coarse",
                "in_kernel": 1,
                "out_fine": False,
                "out_kernel": 1,
                "out_norm": False,
                "window_size": 3,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 3,
                "fs_ratio": 1.0,
                "res_near": True,
                "in_norm": False,
                "in_mode": "coarse",
                "in_kernel": 1,
                "out_fine": False,
                "out_kernel": 1,
                "out_norm": False,
                "window_size": 3,
            },
            input_shape=((2, 24, 24, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 24, 24, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 0.8,
                "res_near": True,
                "in_norm": False,
                "in_mode": "coarse",
                "in_kernel": 1,
                "out_fine": False,
                "out_kernel": 1,
                "out_norm": False,
                "window_size": 3,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 1.0,
                "res_near": False,
                "in_norm": False,
                "in_mode": "coarse",
                "in_kernel": 1,
                "out_fine": False,
                "out_kernel": 1,
                "out_norm": False,
                "window_size": 3,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 1.0,
                "res_near": True,
                "in_norm": True,
                "in_mode": "coarse",
                "in_kernel": 1,
                "out_fine": False,
                "out_kernel": 1,
                "out_norm": False,
                "window_size": 3,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 1.0,
                "res_near": True,
                "in_norm": False,
                "in_mode": "h2l",
                "in_kernel": 1,
                "out_fine": False,
                "out_kernel": 1,
                "out_norm": False,
                "window_size": 3,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 1.0,
                "res_near": True,
                "in_norm": False,
                "in_mode": "l2h",
                "in_kernel": 1,
                "out_fine": False,
                "out_kernel": 1,
                "out_norm": False,
                "window_size": 3,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 1.0,
                "res_near": True,
                "in_norm": False,
                "in_mode": "coarse",
                "in_kernel": 3,
                "out_fine": False,
                "out_kernel": 1,
                "out_norm": False,
                "window_size": 3,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 1.0,
                "res_near": True,
                "in_norm": False,
                "in_mode": "coarse",
                "in_kernel": 1,
                "out_fine": True,
                "out_kernel": 1,
                "out_norm": False,
                "window_size": 3,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 1.0,
                "res_near": True,
                "in_norm": False,
                "in_mode": "coarse",
                "in_kernel": 1,
                "out_fine": False,
                "out_kernel": 3,
                "out_norm": False,
                "window_size": 3,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 1.0,
                "res_near": True,
                "in_norm": False,
                "in_mode": "coarse",
                "in_kernel": 1,
                "out_fine": False,
                "out_kernel": 1,
                "out_norm": True,
                "window_size": 3,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )
        self.run_layer_test(
            GlaFeatureAlignment,
            init_kwargs={
                "filters": 6,
                "scale": 2,
                "fs_ratio": 1.0,
                "res_near": True,
                "in_norm": False,
                "in_mode": "coarse",
                "in_kernel": 1,
                "out_fine": False,
                "out_kernel": 1,
                "out_norm": False,
                "window_size": 5,
            },
            input_shape=((2, 16, 16, 4), (2, 8, 8, 8)),
            input_dtype=("float32",) * 2,
            expected_output_shape=(2, 16, 16, 6),
            expected_output_dtype="float32",
        )


# class TestSeFeatureSelection(testing.TestCase):
#     def test_layer(self):
#         self.run_layer_test(
#             SeFeatureSelection,
#             init_kwargs={
#                 "ratio": 0.5,
#             },
#             input_shape=(2, 16, 16, 36),
#             input_dtype="float32",
#             expected_output_shape=(2, 16, 16, 18),
#             expected_output_dtype="float32",
#         )
#
#
# class TestLocalAttention(testing.TestCase):
#     def test_layer(self):
#         self.run_layer_test(
#             LocalAttention,
#             init_kwargs={
#                 "scale": 2,
#                 "window_size": 3,
#                 "num_heads": 3,
#                 "qk_units": None,
#                 "qkv_bias": True,
#                 "cpb_units": 512,
#                 "dilation_rate": 1,
#                 "proj_bias": True,
#             },
#             input_shape=((2, 16, 16, 36), (2, 8, 8, 72)),
#             input_dtype=("float32",) * 2,
#             expected_output_shape=(2, 16, 16, 72),
#             expected_output_dtype="float32",
#         )
#         self.run_layer_test(
#             LocalAttention,
#             init_kwargs={
#                 "scale": 3,
#                 "window_size": 3,
#                 "num_heads": 3,
#                 "qk_units": None,
#                 "qkv_bias": True,
#                 "cpb_units": 512,
#                 "dilation_rate": 1,
#                 "proj_bias": True,
#             },
#             input_shape=((2, 24, 24, 36), (2, 8, 8, 72)),
#             input_dtype=("float32",) * 2,
#             expected_output_shape=(2, 24, 24, 72),
#             expected_output_dtype="float32",
#         )
#         self.run_layer_test(
#             LocalAttention,
#             init_kwargs={
#                 "scale": 2,
#                 "window_size": 5,
#                 "num_heads": 3,
#                 "qk_units": None,
#                 "qkv_bias": True,
#                 "cpb_units": 512,
#                 "dilation_rate": 1,
#                 "proj_bias": True,
#             },
#             input_shape=((2, 16, 16, 36), (2, 8, 8, 72)),
#             input_dtype=("float32",) * 2,
#             expected_output_shape=(2, 16, 16, 72),
#             expected_output_dtype="float32",
#         )
#         self.run_layer_test(
#             LocalAttention,
#             init_kwargs={
#                 "scale": 2,
#                 "window_size": 3,
#                 "num_heads": 2,
#                 "qk_units": None,
#                 "qkv_bias": True,
#                 "cpb_units": 512,
#                 "dilation_rate": 1,
#                 "proj_bias": True,
#             },
#             input_shape=((2, 16, 16, 36), (2, 8, 8, 72)),
#             input_dtype=("float32",) * 2,
#             expected_output_shape=(2, 16, 16, 72),
#             expected_output_dtype="float32",
#         )
#         self.run_layer_test(
#             LocalAttention,
#             init_kwargs={
#                 "scale": 2,
#                 "window_size": 3,
#                 "num_heads": 3,
#                 "qk_units": 8,
#                 "qkv_bias": True,
#                 "cpb_units": 512,
#                 "dilation_rate": 1,
#                 "proj_bias": True,
#             },
#             input_shape=((2, 16, 16, 36), (2, 8, 8, 72)),
#             input_dtype=("float32",) * 2,
#             expected_output_shape=(2, 16, 16, 72),
#             expected_output_dtype="float32",
#         )
#         self.run_layer_test(
#             LocalAttention,
#             init_kwargs={
#                 "scale": 2,
#                 "window_size": 3,
#                 "num_heads": 3,
#                 "qk_units": None,
#                 "qkv_bias": False,
#                 "cpb_units": 512,
#                 "dilation_rate": 1,
#                 "proj_bias": True,
#             },
#             input_shape=((2, 16, 16, 36), (2, 8, 8, 72)),
#             input_dtype=("float32",) * 2,
#             expected_output_shape=(2, 16, 16, 72),
#             expected_output_dtype="float32",
#         )
#         self.run_layer_test(
#             LocalAttention,
#             init_kwargs={
#                 "scale": 2,
#                 "window_size": 3,
#                 "num_heads": 3,
#                 "qk_units": None,
#                 "qkv_bias": True,
#                 "cpb_units": 64,
#                 "dilation_rate": 1,
#                 "proj_bias": True,
#             },
#             input_shape=((2, 16, 16, 36), (2, 8, 8, 72)),
#             input_dtype=("float32",) * 2,
#             expected_output_shape=(2, 16, 16, 72),
#             expected_output_dtype="float32",
#         )
#         self.run_layer_test(
#             LocalAttention,
#             init_kwargs={
#                 "scale": 2,
#                 "window_size": 3,
#                 "num_heads": 3,
#                 "qk_units": None,
#                 "qkv_bias": True,
#                 "cpb_units": 512,
#                 "dilation_rate": 2,
#                 "proj_bias": True,
#             },
#             input_shape=((2, 16, 16, 36), (2, 8, 8, 72)),
#             input_dtype=("float32",) * 2,
#             expected_output_shape=(2, 16, 16, 72),
#             expected_output_dtype="float32",
#         )
#         self.run_layer_test(
#             LocalAttention,
#             init_kwargs={
#                 "scale": 2,
#                 "window_size": 3,
#                 "num_heads": 3,
#                 "qk_units": None,
#                 "qkv_bias": True,
#                 "cpb_units": 512,
#                 "dilation_rate": 1,
#                 "proj_bias": False,
#             },
#             input_shape=((2, 16, 16, 36), (2, 8, 8, 72)),
#             input_dtype=("float32",) * 2,
#             expected_output_shape=(2, 16, 16, 72),
#             expected_output_dtype="float32",
#         )
