from segme.model.segmentation.deeplab_v3_plus.model import build_deeplab_v3_plus
from segme.model.segmentation.deeplab_v3_plus.hattn import build_deeplab_v3_plus_with_hierarchical_attention
from segme.model.segmentation.deeplab_v3_plus.rend import build_deeplab_v3_plus_with_point_rend
